# Deployment Configuration

# Docker settings
docker:
  image_name: jurisai
  image_tag: latest
  container_name: jurisai-app
  ports:
    - "8501:8501"  # Streamlit port
  environment:
    - PYTHONUNBUFFERED=1
    - STREAMLIT_SERVER_PORT=8501
    - STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Resource limits
resources:
  memory: "2Gi"
  cpu: "1"
  
# Application settings
app:
  workers: 4
  timeout: 300
  max_requests: 1000
  log_level: "INFO"

# Health check
health_check:
  endpoint: "/_stcore/health"
  interval: "30s"
  timeout: "10s"
  retries: 3

# Volumes
volumes:
  - name: data
    path: /app/data
  - name: models
    path: /app/models
  - name: logs
    path: /app/logs 