[server]
headless = true
port = 8080
enableCORS = false
[theme]
primaryColor="#c59d4f"              # Elegant gold (for highlights & accents)
backgroundColor="#1a1f26"           # Deep navy-charcoal (dark base for contrast)
secondaryBackgroundColor="#2b3240"  # Muted steel blue (for cards, inputs, panels)
textColor="#e6e6ea"                 # Off-white text (clean on dark bg)
font="serif"                        # Classic, trustworthy vibe