name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
      - '**.ipynb'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
      - '**.ipynb'

# Prevent concurrent documentation builds
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: "pip"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          
      - name: Build documentation
        run: |
          jupyter-book build . --config docs/_config.yml --toc docs/_toc.yml
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true  # Keep gh-pages branch clean 