name: Documentation

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '**.md'
      - '**.ipynb'
      - 'src/**/*.py'  # Check Python files for docstrings
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - '**.md'
      - '**.ipynb'
      - 'src/**/*.py'

# Prevent concurrent documentation builds
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: "pip"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          
      - name: Check RST documentation
        run: |
          doc8 docs/ || echo "::warning::Documentation style issues found"

      - name: Check Python docstrings
        run: |
          pydocstyle src/ || echo "::warning::Docstring style issues found"

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: "pip"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          
      - name: Build documentation
        run: |
          # Create _build directory if it doesn't exist
          mkdir -p _build
          # Build the documentation
          jupyter-book build . --config docs/_config.yml --toc docs/_toc.yml
        
      - name: List built files
        run: |
          ls -la _build/html || echo "No _build/html directory found"
          
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: _build/html
          retention-days: 5

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true  # Keep gh-pages branch clean 